# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import train_pb2 as train__pb2


class TrainerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Train = channel.stream_stream(
        '/Trainer/Train',
        request_serializer=train__pb2.Tensor.SerializeToString,
        response_deserializer=train__pb2.Tensor.FromString,
        )


class TrainerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Train(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrainerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Train': grpc.stream_stream_rpc_method_handler(
          servicer.Train,
          request_deserializer=train__pb2.Tensor.FromString,
          response_serializer=train__pb2.Tensor.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Trainer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
