# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='train.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0btrain.proto\"3\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x64type\x18\x03 \x01(\t2*\n\x07Trainer\x12\x1f\n\x05Train\x12\x07.Tensor\x1a\x07.Tensor\"\x00(\x01\x30\x01\x62\x06proto3')
)




_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Tensor.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Tensor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='Tensor.dtype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), dict(
  DESCRIPTOR = _TENSOR,
  __module__ = 'train_pb2'
  # @@protoc_insertion_point(class_scope:Tensor)
  ))
_sym_db.RegisterMessage(Tensor)



_TRAINER = _descriptor.ServiceDescriptor(
  name='Trainer',
  full_name='Trainer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=68,
  serialized_end=110,
  methods=[
  _descriptor.MethodDescriptor(
    name='Train',
    full_name='Trainer.Train',
    index=0,
    containing_service=None,
    input_type=_TENSOR,
    output_type=_TENSOR,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINER)

DESCRIPTOR.services_by_name['Trainer'] = _TRAINER

# @@protoc_insertion_point(module_scope)
